### ISSUE TITLE
فعال نشدن کلاینت چابک روی اندروید پروژه یونیتی

### ISSUE THREAD

**Issue by Ario92** [Husseinhj/chabok-starter-unity#1]
برروی یونیتی پلاگین چابک را قرار دادم. کلید کاربر هم ایجاد شده و کاربر را در چابک ثبت می کند(حداقل سمت گوشی) اما در پنل هیچ دستگاهی را نشان نمیدهد.

**Comment by Husseinhj** [comment]
<p dir="rtl">آیا متد register چابک رو فراخوانی کردید؟</p>

**Comment by Ario92** [comment]
``` c#
public class MainInit : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log("chabok start");

        AndroidJavaObject unityPlayerActivity = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
        AndroidJavaObject currentActivity = unityPlayerActivity.GetStatic<AndroidJavaObject>("currentActivity");
        AndroidJavaObject context = currentActivity.Call<AndroidJavaObject>("getApplicationContext");

        var chabok = new ChabokPush();
        chabok.Init(context,
             unityPlayerActivity,
              "*******/************",
               "*************************************",
                "********************",
                 "*************************");
        chabok.SetDevelopment(true);

        //chabok.SetDefaulTracker("TRACKER_ID");

        var userId = chabok.GetUserId();
        Debug.Log("chabok");
        Debug.Log(userId);
        if (userId != null)
        {
            chabok.Register(userId);
            Debug.Log("chabok by user_id");
        }
        else
        {
            chabok.RegisterAsGuest();
            Debug.Log("chabok RegisterAsGuest");

        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
```

 الان مقدار کد کاربر(*) را هم بهم میده و متد رجیستر بدون خطا اجرا میشه اما داخل پنل کاربری میگه کلاینت چابک روی هیچ دستگاهی فعال نشده است.
![Capture](https://user-images.githubusercontent.com/29370234/62012076-b5834300-b196-11e9-81a2-74bf5d79d284.PNG)


(*) userId

**Comment by Ario92** [comment]
واقعا سیستم پشتیبانی ضعیفی دارید.

**Comment by Husseinhj** [comment]
<p dir="rtl">@Ario92 عذرخواهی می‌کنم برای تاخیر در پاسخ issue شما.</p>
<p dir="rtl">خطایی در logcat  اندروید دریافت می‌کنید؟ ( در صورت مشاهده خطا لاگ آن را برای ما ارسال کنید)</p>
<p dir="rtl">از کدام نسخه unity استفاده می‌کنید؟</p>
<p dir="rtl">لطفا appId پنل‌تان را برای ما ارسال کنید</p>

**Comment by Ario92** [comment]
مشکل را  پ

> @Ario92 عذرخواهی می‌کنم برای تاخیر در پاسخ issue شما.
> 
> خطایی در logcat اندروید دریافت می‌کنید؟ ( در صورت مشاهده خطا لاگ آن را برای ما ارسال کنید)
> 
> از کدام نسخه unity استفاده می‌کنید؟
> 
> لطفا appId پنل‌تان را برای ما ارسال کنید

سلام مجدد
appid: ahajadbe 
unity 2017
مشکل حل شد و الان مشکل جدید تری پیدا کرده ام. 
نوتیف چابک زمانی که بازی باز است ارسال می شود و زمانی که بسته است پوش نوتیف نمی آید. اطلاعات سمت اف سی ام را چند بار چک کردم و تا آنجایی که بخش رفع مشکل اندروید را میتوانستم بررسی کردم.
در صورت لزوم هر اطلاعاتی که لازم هست را بفرمایید از طریق ایمیل برایتان ارسال کنم ولی رفع سریع این مشکل برایم حیاتی شده است.
با تشکر از شما
@Husseinhj

**Comment by Husseinhj** [comment]
این موضوع رو بررسی می‌کنیم و بهتون در همین هفته اطلاع خواهیم داد

**Comment by Ario92** [comment]
حرفم را در رابطه با پشتیبانی پس میگیرم.
ممنون از پیگیر بودنتون.


مشکل حل شد پس این ایشو رو میبندم
