### ISSUE TITLE
مشکل در FCM

### ISSUE THREAD

**Issue by Ario92** [Husseinhj/chabok-starter-unity#2]
من از سیستم چابک برای پروژه یونیتی استفاده میکنم.
پیام های چابک زمانی که پروژه باز است دریافت میشود ولی زمانی که پروژه بسته می شود پیامی دریافت نمی شود. 
sender ID هم به درستی وارد شده است

**Comment by Husseinhj** [comment]
<p dir="rtl">این موضوع به صورت ارتباط تلفنی در نسخه آخر کتابخانه unity چابک حل شده. لطفا در صورت مشاهده مورد مشابه،  issue رو باز کنین و مارو مطلع کنید</p>
